FROM node:20-bookworm-slim

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY prisma/ ./prisma/
RUN npm ci

COPY . .

RUN npm run prisma:generate
RUN rm -rf dist tsconfig.tsbuildinfo tsconfig.build.tsbuildinfo && npm run build

EXPOSE 4000

CMD ["sh", "-c", "if [ -f dist/main.js ]; then node dist/main.js; else echo 'No dist/main.js found' && exit 1; fi"]
